### ISSUE TITLE
Implement localstack data persistence using `DATA_DIR`

### ISSUE THREAD

**Issue by leothomas** [NASA-IMPACT/nasa-apt#387]
With the following environment variables in `docker-compose.yml`: 
```
environment: 
  DATA_DIR: /tmp/localstack/data
  HOST_TMP_FOLDER: ${TMPDIR}
volumes:
  - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
```
localstack resources (such as cognito instance) will be persisted between session. (The challenge then becomes verifying if the resources exist or not before createing them in the startup script)
