### ISSUE TITLE
Cloudformation Template for API stack

### ISSUE THREAD

**Issue by leothomas** [NASA-IMPACT/nasa-apt#408]
Generated using the `cdk synth ${STACK_NAME}` command. To be updated with any modifications to the backend infrastructure. 

**Note:** this template was generated for the `dev` stack, so the resource names will not be the same as the production stack

```YAML

Resources:
  nasaaptapilambdadevvpc471C5012:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: default
      Tags:
        - Key: Client
          Value: NASA Impact
        - Key: Name
          Value: nasa-apt-api-lambda-dev/nasa-apt-api-lambda-dev-vpc
        - Key: Owner
          Value: Leo Thomas
        - Key: Project
          Value: nasa-apt-api
        - Key: Stack
          Value: dev
    Metadata:
      aws:cdk:path: nasa-apt-api-lambda-dev/nasa-apt-api-lambda-dev-vpc/Resource
  nasaaptapilambdadevvpcPublicSubnet1Subnet1SubnetC551FD2B:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.0.0/17
      VpcId:
        Ref: nasaaptapilambdadevvpc471C5012
      AvailabilityZone:
        Fn::Select:
          - 0
          - Fn::GetAZs: ""
      MapPublicIpOnLaunch: true
      Tags:
        - Key: aws-cdk:subnet-name
          Value: PublicSubnet1
        - Key: aws-cdk:subnet-type
          Value: Public
        - Key: Client
          Value: NASA Impact
        - Key: Name
          Value: nasa-apt-api-lambda-dev/nasa-apt-api-lambda-dev-vpc/PublicSubnet1Subnet1
        - Key: Owner
          Value: Leo Thomas
        - Key: Project
          Value: nasa-apt-api
        - Key: Stack
          Value: dev
    Metadata:
      aws:cdk:path: nasa-apt-api-lambda-dev/nasa-apt-api-lambda-dev-vpc/PublicSubnet1Subnet1/Subnet
  nasaaptapilambdadevvpcPublicSubnet1Subnet1RouteTable9F1D457C:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: nasaaptapilambdadevvpc471C5012
      Tags:
        - Key: Client
          Value: NASA Impact
        - Key: Name
          Value: nasa-apt-api-lambda-dev/nasa-apt-api-lambda-dev-vpc/PublicSubnet1Subnet1
        - Key: Owner
          Value: Leo Thomas
        - Key: Project
          Value: nasa-apt-api
        - Key: Stack
          Value: dev
    Metadata:
      aws:cdk:path: nasa-apt-api-lambda-dev/nasa-apt-api-lambda-dev-vpc/PublicSubnet1Subnet1/RouteTable
  nasaaptapilambdadevvpcPublicSubnet1Subnet1RouteTableAssociation226F314B:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: nasaaptapilambdadevvpcPublicSubnet1Subnet1RouteTable9F1D457C
      SubnetId:
        Ref: nasaaptapilambdadevvpcPublicSubnet1Subnet1SubnetC551FD2B
    Metadata:
      aws:cdk:path: nasa-apt-api-lambda-dev/nasa-apt-api-lambda-dev-vpc/PublicSubnet1Subnet1/RouteTableAssociation
  nasaaptapilambdadevvpcPublicSubnet1Subnet1DefaultRouteE9B564A7:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Ref: nasaaptapilambdadevvpcPublicSubnet1Subnet1RouteTable9F1D457C
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: nasaaptapilambdadevvpcIGWE0048DFE
    DependsOn:
      - nasaaptapilambdadevvpcVPCGWC0D972AC
    Metadata:
      aws:cdk:path: nasa-apt-api-lambda-dev/nasa-apt-api-lambda-dev-vpc/PublicSubnet1Subnet1/DefaultRoute
  nasaaptapilambdadevvpcPublicSubnet1Subnet2Subnet9F859644:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.128.0/17
      VpcId:
        Ref: nasaaptapilambdadevvpc471C5012
      AvailabilityZone:
        Fn::Select:
          - 1
          - Fn::GetAZs: ""
      MapPublicIpOnLaunch: true
      Tags:
        - Key: aws-cdk:subnet-name
          Value: PublicSubnet1
        - Key: aws-cdk:subnet-type
          Value: Public
        - Key: Client
          Value: NASA Impact
        - Key: Name
          Value: nasa-apt-api-lambda-dev/nasa-apt-api-lambda-dev-vpc/PublicSubnet1Subnet2
        - Key: Owner
          Value: Leo Thomas
        - Key: Project
          Value: nasa-apt-api
        - Key: Stack
          Value: dev
    Metadata:
      aws:cdk:path: nasa-apt-api-lambda-dev/nasa-apt-api-lambda-dev-vpc/PublicSubnet1Subnet2/Subnet
  nasaaptapilambdadevvpcPublicSubnet1Subnet2RouteTableD9CF5674:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: nasaaptapilambdadevvpc471C5012
      Tags:
        - Key: Client
          Value: NASA Impact
        - Key: Name
          Value: nasa-apt-api-lambda-dev/nasa-apt-api-lambda-dev-vpc/PublicSubnet1Subnet2
        - Key: Owner
          Value: Leo Thomas
        - Key: Project
          Value: nasa-apt-api
        - Key: Stack
          Value: dev
    Metadata:
      aws:cdk:path: nasa-apt-api-lambda-dev/nasa-apt-api-lambda-dev-vpc/PublicSubnet1Subnet2/RouteTable
  nasaaptapilambdadevvpcPublicSubnet1Subnet2RouteTableAssociation2D8E5762:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: nasaaptapilambdadevvpcPublicSubnet1Subnet2RouteTableD9CF5674
      SubnetId:
        Ref: nasaaptapilambdadevvpcPublicSubnet1Subnet2Subnet9F859644
    Metadata:
      aws:cdk:path: nasa-apt-api-lambda-dev/nasa-apt-api-lambda-dev-vpc/PublicSubnet1Subnet2/RouteTableAssociation
  nasaaptapilambdadevvpcPublicSubnet1Subnet2DefaultRouteFCB1A666:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Ref: nasaaptapilambdadevvpcPublicSubnet1Subnet2RouteTableD9CF5674
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: nasaaptapilambdadevvpcIGWE0048DFE
    DependsOn:
      - nasaaptapilambdadevvpcVPCGWC0D972AC
    Metadata:
      aws:cdk:path: nasa-apt-api-lambda-dev/nasa-apt-api-lambda-dev-vpc/PublicSubnet1Subnet2/DefaultRoute
  nasaaptapilambdadevvpcIGWE0048DFE:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Client
          Value: NASA Impact
        - Key: Name
          Value: nasa-apt-api-lambda-dev/nasa-apt-api-lambda-dev-vpc
        - Key: Owner
          Value: Leo Thomas
        - Key: Project
          Value: nasa-apt-api
        - Key: Stack
          Value: dev
    Metadata:
      aws:cdk:path: nasa-apt-api-lambda-dev/nasa-apt-api-lambda-dev-vpc/IGW
  nasaaptapilambdadevvpcVPCGWC0D972AC:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: nasaaptapilambdadevvpc471C5012
      InternetGatewayId:
        Ref: nasaaptapilambdadevvpcIGWE0048DFE
    Metadata:
      aws:cdk:path: nasa-apt-api-lambda-dev/nasa-apt-api-lambda-dev-vpc/VPCGW
  nasaaptapilambdadevrdssecuritygroup83CD9F15:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for nasa-apt-api-lambda-dev-downloader-rds
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic by default
          IpProtocol: "-1"
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          Description: Allow all traffic for Postgres
          FromPort: 5432
          IpProtocol: tcp
          ToPort: 5432
      Tags:
        - Key: Client
          Value: NASA Impact
        - Key: Owner
          Value: Leo Thomas
        - Key: Project
          Value: nasa-apt-api
        - Key: Stack
          Value: dev
      VpcId:
        Ref: nasaaptapilambdadevvpc471C5012
    Metadata:
      aws:cdk:path: nasa-apt-api-lambda-dev/nasa-apt-api-lambda-dev-rds-security-group/Resource
  nasaaptapilambdadevpostgresdbSubnetGroupC45D3394:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for nasa-apt-api-lambda-dev-postgres-db database
      SubnetIds:
        - Ref: nasaaptapilambdadevvpcPublicSubnet1Subnet1SubnetC551FD2B
        - Ref: nasaaptapilambdadevvpcPublicSubnet1Subnet2Subnet9F859644
      Tags:
        - Key: Client
          Value: NASA Impact
        - Key: Owner
          Value: Leo Thomas
        - Key: Project
          Value: nasa-apt-api
        - Key: Stack
          Value: dev
    Metadata:
      aws:cdk:path: nasa-apt-api-lambda-dev/nasa-apt-api-lambda-dev-postgres-db/SubnetGroup/Default
  nasaaptapilambdadevnasaaptapilambdadevpostgresdbSecret04BCE63B3fdaad7efa858a3daf9490cf0a702aeb:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description:
        Fn::Join:
          - ""
          - - "Generated by the CDK for stack: "
            - Ref: AWS::StackName
      GenerateSecretString:
        ExcludeCharacters: " %+~`#$&*()|[]{}:;<>?!'/@\"\\"
        GenerateStringKey: password
        PasswordLength: 30
        SecretStringTemplate: '{"username":"masteruser"}'
      Name: nasa-apt-api-lambda-dev-database-secrets
      Tags:
        - Key: Client
          Value: NASA Impact
        - Key: Owner
          Value: Leo Thomas
        - Key: Project
          Value: nasa-apt-api
        - Key: Stack
          Value: dev
    Metadata:
      aws:cdk:path: nasa-apt-api-lambda-dev/nasa-apt-api-lambda-dev-postgres-db/Secret/Resource
  nasaaptapilambdadevpostgresdbSecretAttachment1989EE57:
    Type: AWS::SecretsManager::SecretTargetAttachment
    Properties:
      SecretId:
        Ref: nasaaptapilambdadevnasaaptapilambdadevpostgresdbSecret04BCE63B3fdaad7efa858a3daf9490cf0a702aeb
      TargetId:
        Ref: nasaaptapilambdadevpostgresdbF3FA777B
      TargetType: AWS::RDS::DBInstance
    Metadata:
      aws:cdk:path: nasa-apt-api-lambda-dev/nasa-apt-api-lambda-dev-postgres-db/Secret/Attachment/Resource
  nasaaptapilambdadevpostgresdbF3FA777B:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceClass: db.t2.small
      AllocatedStorage: "10"
      BackupRetentionPeriod: 7
      CopyTagsToSnapshot: true
      DBName: nasadb
      DBSubnetGroupName:
        Ref: nasaaptapilambdadevpostgresdbSubnetGroupC45D3394
      DeletionProtection: false
      Engine: postgres
      MasterUsername: masteruser
      MasterUserPassword:
        Fn::Join:
          - ""
          - - "{{resolve:secretsmanager:"
            - Ref: nasaaptapilambdadevnasaaptapilambdadevpostgresdbSecret04BCE63B3fdaad7efa858a3daf9490cf0a702aeb
            - :SecretString:password::}}
      PubliclyAccessible: true
      StorageType: gp2
      Tags:
        - Key: Client
          Value: NASA Impact
        - Key: Owner
          Value: Leo Thomas
        - Key: Project
          Value: nasa-apt-api
        - Key: Stack
          Value: dev
      VPCSecurityGroups:
        - Fn::GetAtt:
            - nasaaptapilambdadevrdssecuritygroup83CD9F15
            - GroupId
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: nasa-apt-api-lambda-dev/nasa-apt-api-lambda-dev-postgres-db/Resource
  nasaaptapilambdadev68771DD6:
    Type: AWS::S3::Bucket
    Properties:
      Tags:
        - Key: Client
          Value: NASA Impact
        - Key: Owner
          Value: Leo Thomas
        - Key: Project
          Value: nasa-apt-api
        - Key: Stack
          Value: dev
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: nasa-apt-api-lambda-dev/nasa-apt-api-lambda-dev/Resource
  nasaaptapilambdadevelasticsearchdomain95CF8C14:
    Type: AWS::Elasticsearch::Domain
    Properties:
      CognitoOptions:
        Enabled: false
      DomainEndpointOptions:
        EnforceHTTPS: false
        TLSSecurityPolicy: Policy-Min-TLS-1-0-2019-07
      DomainName: a-apt-api-lambda-dev-elastic
      EBSOptions:
        EBSEnabled: true
        Iops: 0
        VolumeSize: 10
        VolumeType: gp2
      ElasticsearchClusterConfig:
        DedicatedMasterEnabled: false
        InstanceCount: 1
        InstanceType: t2.small.elasticsearch
        ZoneAwarenessEnabled: false
      ElasticsearchVersion: "7.7"
      EncryptionAtRestOptions:
        Enabled: false
      LogPublishingOptions: {}
      NodeToNodeEncryptionOptions:
        Enabled: false
      Tags:
        - Key: Client
          Value: NASA Impact
        - Key: Owner
          Value: Leo Thomas
        - Key: Project
          Value: nasa-apt-api
        - Key: Stack
          Value: dev
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: nasa-apt-api-lambda-dev/nasa-apt-api-lambda-dev-elasticsearch-domain/Resource
  nasaaptapilambdadevlambdaServiceRoleC6B5E01C:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Tags:
        - Key: Client
          Value: NASA Impact
        - Key: Owner
          Value: Leo Thomas
        - Key: Project
          Value: nasa-apt-api
        - Key: Stack
          Value: dev
    Metadata:
      aws:cdk:path: nasa-apt-api-lambda-dev/nasa-apt-api-lambda-dev-lambda/ServiceRole/Resource
  nasaaptapilambdadevlambdaServiceRoleDefaultPolicy515128A4:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: ses:SendEmail
            Effect: Allow
            Resource: "*"
          - Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Effect: Allow
            Resource: "*"
          - Action:
              - secretsmanager:GetSecretValue
              - secretsmanager:DescribeSecret
            Effect: Allow
            Resource:
              Ref: nasaaptapilambdadevpostgresdbSecretAttachment1989EE57
          - Action:
              - es:ESHttpGet
              - es:ESHttpHead
              - es:ESHttpDelete
              - es:ESHttpPost
              - es:ESHttpPut
              - es:ESHttpPatch
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - nasaaptapilambdadevelasticsearchdomain95CF8C14
                  - Arn
              - Fn::Join:
                  - ""
                  - - Fn::GetAtt:
                        - nasaaptapilambdadevelasticsearchdomain95CF8C14
                        - Arn
                    - /*
          - Action:
              - s3:GetObject*
              - s3:GetBucket*
              - s3:List*
              - s3:DeleteObject*
              - s3:PutObject*
              - s3:Abort*
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - nasaaptapilambdadev68771DD6
                  - Arn
              - Fn::Join:
                  - ""
                  - - Fn::GetAtt:
                        - nasaaptapilambdadev68771DD6
                        - Arn
                    - /*
          - Action: cognito-idp:AdminGetUser
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - nasaaptapilambdadevusersC51738B0
                - Arn
          - Action:
              - cognito-idp:ListUserPools
              - cognito-idp:ListUserPoolClients
              - cognito-idp:ListUsersInGroup
            Effect: Allow
            Resource: "*"
        Version: "2012-10-17"
      PolicyName: nasaaptapilambdadevlambdaServiceRoleDefaultPolicy515128A4
      Roles:
        - Ref: nasaaptapilambdadevlambdaServiceRoleC6B5E01C
    Metadata:
      aws:cdk:path: nasa-apt-api-lambda-dev/nasa-apt-api-lambda-dev-lambda/ServiceRole/DefaultPolicy/Resource
  nasaaptapilambdadevlambdaBF38D18E:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ImageUri:
          Fn::Join:
            - ""
            - - Ref: AWS::AccountId
              - .dkr.ecr.
              - Ref: AWS::Region
              - "."
              - Ref: AWS::URLSuffix
              - /aws-cdk/assets:1f68db138122a35df16e9c9a321a40bda16aa94d5ca0cfebf5fa3977a364d0aa
      Role:
        Fn::GetAtt:
          - nasaaptapilambdadevlambdaServiceRoleC6B5E01C
          - Arn
      Environment:
        Variables:
          PROJECT_NAME: nasa-apt-api
          API_VERSION_STRING: /v2
          APT_FRONTEND_URL: https://nasa-apt.surge.sh
          BACKEND_CORS_ORIGINS: "*,http://localhost:9000,http://localhost:3006,https://nasa-apt.surge.sh"
          POSTGRES_ADMIN_CREDENTIALS_ARN:
            Ref: nasaaptapilambdadevpostgresdbSecretAttachment1989EE57
          ELASTICSEARCH_URL:
            Fn::GetAtt:
              - nasaaptapilambdadevelasticsearchdomain95CF8C14
              - DomainEndpoint
          S3_BUCKET:
            Ref: nasaaptapilambdadev68771DD6
          NOTIFICATIONS_FROM: no-reply@ds.io
          MODULE_NAME: nasa_apt.main
          VARIABLE_NAME: app
          USER_POOL_NAME: nasa-apt-api-lambda-dev-users
          APP_CLIENT_NAME: nasa-apt-api-lambda-dev-apt-app-client
      ImageConfig:
        Command:
          - handler.handler
        EntryPoint:
          - /usr/local/bin/python
          - -m
          - awslambdaric
      MemorySize: 1536
      PackageType: Image
      Tags:
        - Key: Client
          Value: NASA Impact
        - Key: Owner
          Value: Leo Thomas
        - Key: Project
          Value: nasa-apt-api
        - Key: Stack
          Value: dev
      Timeout: 120
    DependsOn:
      - nasaaptapilambdadevlambdaServiceRoleDefaultPolicy515128A4
      - nasaaptapilambdadevlambdaServiceRoleC6B5E01C
    Metadata:
      aws:cdk:path: nasa-apt-api-lambda-dev/nasa-apt-api-lambda-dev-lambda/Resource
  nasaaptapilambdadevendpoint8F5D9896:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: nasa-apt-api-lambda-dev-endpoint
      ProtocolType: HTTP
      Tags:
        Client: NASA Impact
        Owner: Leo Thomas
        Project: nasa-apt-api
        Stack: dev
    Metadata:
      aws:cdk:path: nasa-apt-api-lambda-dev/nasa-apt-api-lambda-dev-endpoint/Resource
  nasaaptapilambdadevendpointDefaultRoutenasaaptapilambdadevnasaaptapilambdadevendpointDefaultRoute7F8D7BB7Permission5A2E4BFC:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - nasaaptapilambdadevlambdaBF38D18E
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: nasaaptapilambdadevendpoint8F5D9896
            - /*/*
    Metadata:
      aws:cdk:path: nasa-apt-api-lambda-dev/nasa-apt-api-lambda-dev-endpoint/DefaultRoute/nasaaptapilambdadevnasaaptapilambdadevendpointDefaultRoute7F8D7BB7-Permission
  nasaaptapilambdadevendpointDefaultRouteHttpIntegration5a98baa40c4e39b5fe25fa4ea35ea5c4CFFBE425:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId:
        Ref: nasaaptapilambdadevendpoint8F5D9896
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::GetAtt:
          - nasaaptapilambdadevlambdaBF38D18E
          - Arn
      PayloadFormatVersion: "2.0"
    Metadata:
      aws:cdk:path: nasa-apt-api-lambda-dev/nasa-apt-api-lambda-dev-endpoint/DefaultRoute/HttpIntegration-5a98baa40c4e39b5fe25fa4ea35ea5c4/Resource
  nasaaptapilambdadevendpointDefaultRouteD60F0B80:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId:
        Ref: nasaaptapilambdadevendpoint8F5D9896
      RouteKey: $default
      AuthorizationType: NONE
      Target:
        Fn::Join:
          - ""
          - - integrations/
            - Ref: nasaaptapilambdadevendpointDefaultRouteHttpIntegration5a98baa40c4e39b5fe25fa4ea35ea5c4CFFBE425
    Metadata:
      aws:cdk:path: nasa-apt-api-lambda-dev/nasa-apt-api-lambda-dev-endpoint/DefaultRoute/Resource
  nasaaptapilambdadevendpointDefaultStage38896345:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId:
        Ref: nasaaptapilambdadevendpoint8F5D9896
      StageName: $default
      AutoDeploy: true
      Tags:
        Client: NASA Impact
        Owner: Leo Thomas
        Project: nasa-apt-api
        Stack: dev
    Metadata:
      aws:cdk:path: nasa-apt-api-lambda-dev/nasa-apt-api-lambda-dev-endpoint/DefaultStage/Resource
  nasaaptapilambdadevusersC51738B0:
    Type: AWS::Cognito::UserPool
    Properties:
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
      AutoVerifiedAttributes:
        - email
      Schema:
        - Mutable: true
          Name: preferred_username
          Required: true
      SmsVerificationMessage: The verification code to your new account is {####}
      UsernameAttributes:
        - email
      UserPoolName: nasa-apt-api-lambda-dev-users
      UserPoolTags:
        Client: NASA Impact
        Owner: Leo Thomas
        Project: nasa-apt-api
        Stack: dev
      VerificationMessageTemplate:
        DefaultEmailOption: CONFIRM_WITH_LINK
        EmailMessageByLink: Thank you for signing up to the Algorithm Publication Tool.<br>Please verify you account by clicking on {##Verify Email##}.<br>Sincerely,<br>The NASA APT team
        EmailSubjectByLink: Verify your new account
        SmsMessage: The verification code to your new account is {####}
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: nasa-apt-api-lambda-dev/nasa-apt-api-lambda-dev-users/Resource
  nasaaptapilambdadevusersnasaaptapilambdadevaptappclientD991B198:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId:
        Ref: nasaaptapilambdadevusersC51738B0
      AllowedOAuthFlows:
        - implicit
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthScopes:
        - openid
        - email
        - profile
        - aws.cognito.signin.user.admin
      CallbackURLs:
        - https://nasa-apt.surge.sh
      ClientName: nasa-apt-api-lambda-dev-apt-app-client
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      LogoutURLs:
        - https://nasa-apt.surge.sh
      PreventUserExistenceErrors: LEGACY
      SupportedIdentityProviders:
        - COGNITO
    Metadata:
      aws:cdk:path: nasa-apt-api-lambda-dev/nasa-apt-api-lambda-dev-users/nasa-apt-api-lambda-dev-apt-app-client/Resource
  nasaaptapilambdadevusersnasaaptapilambdadevaptappclientdomainE92FE533:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: nasa-apt-api-lambda-dev
      UserPoolId:
        Ref: nasaaptapilambdadevusersC51738B0
    Metadata:
      aws:cdk:path: nasa-apt-api-lambda-dev/nasa-apt-api-lambda-dev-users/nasa-apt-api-lambda-dev-apt-app-client-domain/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/11SyW7bMBD9ltxppklQJMd6QVOfIshp7iN6KrOWSGE4TGAQ+veSorXUp3nz5nFWPsiHx+/y290P+HIrdTzfB2UJZTgwqLMo0VlPCsX2j3nz3HkWW2sck1cs1s4hR12tTZ0ES3FUHTVra3qREgdUjzJ8dCrFPoqtKHzVaHXwlUFO3IxK6xnfoWpw5mcu1rRKQ8o8iRPYG0aKyldg/ILLtczVW3Mc5tSiYXFA5Unz5ZWs74YCS6IXdHQy7IChAof7OCmYOFDuYnqz2yyJUR0zUR5htxlf9sINrGvBQI0kQy6ZhNm8A9XIiw4nwW0k5nqSYePVOVfJqBfYgGOtHAKpU2zetqCH5WTUiwba6ggy/PRGjYtb4gKp1c4Nx9LQylDavPzBFjYealhoRrGgohWk2zu5s7EH2rdxtuE3pJgssbNOs6XLJq5FQKfrfIfP+Ad+MXfrTqd8ySQ3HzGhdMWapuveuLMufbr8PRLohbK1iQVl+O2QCmubFJvwCLaNvi74hhndeXX/M33fi+LCJ2vun+SLfL7767RekTesW5Rltv8A6hMHTUkDAAA=
    Metadata:
      aws:cdk:path: nasa-apt-api-lambda-dev/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Outputs:
  nasaaptapilambdadevdatabasesecretarn:
    Description: Arn of the SecretsManager instance holding the connection info for Postgres DB
    Value:
      Ref: nasaaptapilambdadevpostgresdbSecretAttachment1989EE57
  nasaaptapilambdadevendpointurl:
    Description: API Gateway endpoint for the APT API
    Value:
      Fn::GetAtt:
        - nasaaptapilambdadevendpoint8F5D9896
        - ApiEndpoint
  nasaaptapilambdadevuserpoolid:
    Description: User Pool ID
    Value:
      Ref: nasaaptapilambdadevusersC51738B0
  nasaaptapilambdadevappclientid:
    Description: User Pool App Client ID
    Value:
      Ref: nasaaptapilambdadevusersnasaaptapilambdadevaptappclientD991B198
  nasaaptapilambdadevdomain:
    Description: User pool domain
    Value:
      Ref: nasaaptapilambdadevusersnasaaptapilambdadevaptappclientdomainE92FE533
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2
```
